version: "3.8"
services:
  wg-easy:
    image: linuxservers/wireguard:latest
    build: .
    # command: npm run serve
    # volumes:
    #   - ./src/:/app/
    environment: 
      # - PASSWORD=p
      - WG_HOST=0.0.0.0
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    privileged: true # for podman issues
    volumes:
      - ./wg-config/server:/etc/wireguard
    # platform: linux/arm64  
    ports:
      - "51830:51820/udp"
      - "51821:51821/tcp"
    # restart: unless-stopped
    entrypoint: node server.js
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.eth0.proxy_ndp=1

  wg-c1:
    image: linuxserver/wireguard:1.0.20210914

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true # for podman issues
    volumes:
     - ./wg-config/client1:/config/
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.eth0.proxy_ndp=1     

  wg-c2:
    image: linuxserver/wireguard:1.0.20210914
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true # for podman issues
    volumes:
     - ./wg-config/client2:/config/
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.eth0.proxy_ndp=1     